apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo
  name: demo
  labels:
    app: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      name: demo
      labels:
        app: demo
    spec:
      containers:
        - name: demo-nginx
          image: 34.30.23.120:30080/demo/demo:50e3944d
          imagePullPolicy: Always
          ports:
            - containerPort: 80
