resources:
- deployment.yml
- service.yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 10.128.0.37:30080/demo/demo
  newTag: 3a2459dd
- name: 34.30.23.120:30080/demo/demo
  newTag: 93a8c193
