apiVersion: v1
kind: Service
metadata:
  namespace: demo
  name: demo
  labels:
    app: demo
spec:
  type: NodePort
  ports:
    - name: demoport
      port: 80
      targetPort: 80
      nodePort: 30088
  selector:
    app: demo
